# Generated by Django 5.2.6 on 2026-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
