# Generated by Django 5.2.12 on 2026-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_farmer_latitude_farmer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop_variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood Irrigation'), ('manual', 'Manual'), ('none', 'Rain-fed Only')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=50, null=True),
        ),
    ]
