# Generated by Django 5.2.6 on 2026-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_farmer_crop_variety_farmer_irrigation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('labor', 'Labor'), ('admin', 'Admin')], default='farmer', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
