# Generated by Django 5.2.6 on 2026-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_farmer_role_alter_farmer_crop_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
