# Generated by Django 5.2.12 on 2026-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_farmer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='assigned_district',
            field=models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('aurangabad', 'Aurangabad'), ('beed', 'Beed'), ('bidar', 'Bidar'), ('buldhana', 'Buldhana'), ('chandrapur', 'Chandrapur'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('jalna', 'Jalna'), ('kolhapur', 'Kolhapur'), ('latur', 'Latur'), ('mumbai_city', 'Mumbai City'), ('mumbai_suburban', 'Mumbai Suburban'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('osmanabad', 'Osmanabad'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('sindhudurg', 'Sindhudurg'), ('solapur', 'Solapur'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(blank=True, choices=[('ahmednagar', 'Ahmednagar'), ('akola', 'Akola'), ('amravati', 'Amravati'), ('aurangabad', 'Aurangabad'), ('beed', 'Beed'), ('bidar', 'Bidar'), ('buldhana', 'Buldhana'), ('chandrapur', 'Chandrapur'), ('dhule', 'Dhule'), ('gadchiroli', 'Gadchiroli'), ('gondia', 'Gondia'), ('hingoli', 'Hingoli'), ('jalgaon', 'Jalgaon'), ('jalna', 'Jalna'), ('kolhapur', 'Kolhapur'), ('latur', 'Latur'), ('mumbai_city', 'Mumbai City'), ('mumbai_suburban', 'Mumbai Suburban'), ('nagpur', 'Nagpur'), ('nanded', 'Nanded'), ('nandurbar', 'Nandurbar'), ('nashik', 'Nashik'), ('osmanabad', 'Osmanabad'), ('palghar', 'Palghar'), ('parbhani', 'Parbhani'), ('pune', 'Pune'), ('raigad', 'Raigad'), ('ratnagiri', 'Ratnagiri'), ('sangli', 'Sangli'), ('satara', 'Satara'), ('sindhudurg', 'Sindhudurg'), ('solapur', 'Solapur'), ('thane', 'Thane'), ('wardha', 'Wardha'), ('washim', 'Washim'), ('yavatmal', 'Yavatmal')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('labor', 'Labor'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='farmer', max_length=15),
        ),
    ]
